import "./setup-globals";
import assert from "node:assert/strict";
import { act } from "react";
import { createRoot } from "react-dom/client";
import { LanguageProvider } from "../../src/lib/i18n";
import { SharedText } from "../../src/components/HarvestBoard";
import { actionCalendar, datedActions, workshopGuide } from "../../src/lib/workshopTools";
import type { RoomView } from "../../src/types";
const room = {sessionName:"Ședință, echipă; A", actions:[{id:"a1",text:"Întrebări, fără grabă;\nToți participă",ownerId:"p1",due:"2026-12-31",done:false},{id:"bad",text:"Invalid date",due:"2026-02-31"}]} as RoomView;
assert.equal(datedActions(room).length,1);
const ics = actionCalendar(room,[],"ro",new Date("2026-09-24T10:00:00Z"));
assert.match(ics,/DTEND;VALUE=DATE:20270101/);
assert.match(ics,/Întrebări\\, fără grabă\\;\\nToți participă/);
assert.ok(!ics.includes("ATTENDEE"));
assert.ok(ics.split("\r\n").every(line => new TextEncoder().encode(line).length<=75));
assert.equal(workshopGuide("emotions-camera-mare","ro").steps.length,5);
const root=createRoot(document.getElementById("root")!);
localStorage.setItem("pt.lang","ro");
let calls: string[][]=[];
const render=(value:string)=>act(async()=>root.render(<LanguageProvider><SharedText value={value} label="Team note" disabled={false} maxLength={4000} save={(v,p)=>calls.push([v,p])}/></LanguageProvider>));
await render("Original");
const input=document.querySelector("textarea")!;
const setter=Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,"value")!.set!;
await act(async()=>{setter.call(input,"My draft");input.dispatchEvent(new Event("input",{bubbles:true}));});
await render("Colleague update");
assert.equal(input.value,"My draft","remote updates must preserve local draft");
assert.ok(document.body.textContent?.includes("Colleague update"));
await act(async()=>input.dispatchEvent(new FocusEvent("focusout",{bubbles:true})));
assert.equal(calls.length,0,"conflicting field must not auto-overwrite");
const keep=[...document.querySelectorAll("button")].find(b=>b.textContent?.includes("Păstrează varianta"))!;
await act(async()=>keep.click());
assert.equal(input.value,"Colleague update");
await act(async()=>{setter.call(input,"Next draft");input.dispatchEvent(new Event("input",{bubbles:true}));});
await act(async()=>input.dispatchEvent(new FocusEvent("focusout",{bubbles:true})));
assert.deepEqual(calls,[["Next draft","Colleague update"]]);
await act(async()=>root.unmount());
console.log("PASS calendar date boundaries, escaping, UTF-8 folding, no invitations; collaborative draft and conflict recovery");
