import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { formatClock } from "../lib/format";
import { pick, T, useLang } from "../lib/i18n";
import { store, useStore } from "../store";
import type { PlayerView, RoomView } from "../types";

export default function FacilitatorPanel({ room, players, youId, onClose, onReset }: { room: RoomView; players: PlayerView[]; youId: string; onClose: () => void; onReset: () => void }) {
  const { lang } = useLang();
  const savedNotes = useStore((state) => state.facilitatorNotes);
  const ratings = useStore((state) => state.ratings);
  const [notes, setNotes] = useState(savedNotes);
  const [now, setNow] = useState(Date.now());
  useEffect(() => { setNotes(savedNotes); }, [savedNotes]);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const timerLeft = room.timerEndsAt ? Math.max(0, room.timerEndsAt - now) : null;
  const stages = ["lobby", "brief", "play", "reveal", "debrief", "harvest"] as const;
  const isCanvasRoom = !!room.contentLanguage;

  return (
    <aside className="safe-top safe-bottom fixed inset-y-2 right-2 z-50 flex w-[360px] max-w-[calc(100vw-1rem)] flex-col overflow-hidden rounded-3xl border border-white/15 bg-ink-900/95 text-white shadow-pop backdrop-blur-xl sm:inset-y-4 sm:right-4">
      <header className="flex items-center justify-between border-b border-white/10 p-5"><div><div className="text-[10px] font-bold uppercase tracking-[.24em] text-emerald-300"><T value={{ ro: "Mod facilitator", en: "Facilitator mode" }} /></div><h2 className="font-display mt-1 font-bold">{room.sessionName}</h2></div><button className="h-9 w-9 rounded-xl text-ink-300 hover:bg-white/10" onClick={onClose}>✕</button></header>
      <div className="flex-1 space-y-5 overflow-y-auto p-5">
        <section><Label><T value={{ ro: "Agendă", en: "Agenda" }} /></Label><div className="mt-2 flex flex-wrap gap-1.5">{stages.map((stage) => <button key={stage} onClick={() => stage === "reveal" ? store.sendControl("reveal") : store.sendControl("stage", { stage })} className={`rounded-lg px-2.5 py-1.5 text-[11px] font-bold capitalize ${room.stage === stage ? "bg-brand-500 text-white" : "bg-white/5 text-ink-300 hover:bg-white/10"}`}>{stage}</button>)}</div></section>
        <section><div className="flex items-center justify-between"><Label><T value={{ ro: "Scenă și board", en: "Stage & board" }} /></Label><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${room.boardLocked ? "bg-amber-500/15 text-amber-200" : "bg-emerald-500/15 text-emerald-200"}`}>{room.boardLocked ? "LOCKED" : "OPEN"}</span></div><div className="mt-2 grid grid-cols-2 gap-2">{room.stage === "lobby" ? <button className="btn-primary btn-sm col-span-2" onClick={() => store.sendControl("start")}>▶ <T value={{ ro: "Start pentru toți", en: "Start for everyone" }} /></button> : <button className="btn btn-dark btn-sm" onClick={() => store.sendControl("lock", { locked: !room.boardLocked })}>{room.boardLocked ? "🔓 Unlock" : "🔒 Lock"}</button>}{!isCanvasRoom && room.stage !== "lobby" && <button className="btn btn-dark btn-sm" onClick={() => store.sendControl("reveal")}>👁 <T value={{ ro: "Reveal", en: "Reveal" }} /></button>}<button className="btn btn-dark btn-sm" onClick={() => store.sendControl("stage", { stage: "debrief" })}>💬 Debrief</button><button className="btn btn-dark btn-sm" onClick={() => store.sendControl("stage", { stage: "harvest" })}>🌾 Harvest</button></div>{isCanvasRoom && !room.completed && room.stage === "play" && <button className="btn-primary btn-sm mt-2 w-full" onClick={() => confirm(lang === "ro" ? "Declanșezi finalizarea compoziției? Foia se îngheață pentru toată echipa." : "Trigger completion? The sheet freezes for the whole team.") && store.sendControl("complete")}>✅ <T value={{ ro: "Finalizează compoziția", en: "Complete composition" }} /></button>}</section>
        <section><div className="flex items-center justify-between"><Label><T value={{ ro: "Cronometru", en: "Timer" }} /></Label>{timerLeft !== null && <b className={`font-mono text-lg ${timerLeft === 0 ? "text-rose-300" : "text-white"}`}>{formatClock(timerLeft)}</b>}</div><div className="mt-2 grid grid-cols-5 gap-1.5">{[1, 3, 5, 10].map((minutes) => <button key={minutes} onClick={() => store.sendControl("timer", { seconds: minutes * 60 })} className="rounded-lg bg-white/5 py-2 text-xs font-bold hover:bg-white/10">{minutes}m</button>)}<button onClick={() => store.sendControl("timer", { seconds: 0 })} className="rounded-lg bg-white/5 py-2 text-xs font-bold hover:bg-white/10">✕</button></div></section>
        <section><div className="flex items-center justify-between"><Label><T value={{ ro: "Participanți", en: "People" }} /></Label><span className="text-xs text-ink-400">{players.length}/{room.maxPlayers}</span></div><div className="mt-2 space-y-1.5">{players.map((player) => <div key={player.id} className="flex items-center gap-2 rounded-xl bg-white/[.04] px-3 py-2"><span className="h-2.5 w-2.5 rounded-full" style={{ background: player.color }} /><span className="min-w-0 flex-1 truncate text-sm">{player.name}</span><span className="text-[10px] uppercase text-ink-500">{ratings[player.id]?.done ? "✓ done" : player.lastSeenAt && now - player.lastSeenAt > 60_000 ? "idle" : player.role}</span>{player.id !== youId && <button className="text-xs text-rose-300 hover:text-rose-200" title="Remove" onClick={() => confirm(lang === "ro" ? `Îl elimini pe ${player.name}?` : `Remove ${player.name}?`) && store.sendControl("kick", { playerId: player.id })}>✕</button>}</div>)}</div></section>
        <section><Label><T value={{ ro: "Notițe private", en: "Private notes" }} /></Label><textarea className="mt-2 min-h-28 w-full resize-y rounded-xl border border-white/10 bg-white/5 p-3 text-sm text-white outline-none focus:border-brand-400" value={notes} onChange={(event) => setNotes(event.target.value)} onBlur={() => store.sendControl("notes", { text: notes })} placeholder={lang === "ro" ? "Doar facilitatorul vede aceste notițe…" : "Only the facilitator can see these notes…"} /><p className="mt-1 text-[10px] text-ink-500"><T value={{ ro: "Salvate în sesiune și incluse în exportul privat.", en: "Saved with the session and included in the private export." }} /></p></section>
        <section><Label><T value={{ ro: "Celebrare jigsaw", en: "Jigsaw celebration" }} /></Label><div className="mt-2 grid grid-cols-2 gap-2"><button className={`rounded-xl px-3 py-2 text-xs font-bold ${room.celebrationMode === "team" ? "bg-emerald-500/20 text-emerald-200" : "bg-white/5 text-ink-300"}`} onClick={() => store.sendControl("celebration", { mode: "team" })}>🤝 Team only</button><button className={`rounded-xl px-3 py-2 text-xs font-bold ${room.celebrationMode === "individual" ? "bg-amber-500/20 text-amber-200" : "bg-white/5 text-ink-300"}`} onClick={() => store.sendControl("celebration", { mode: "individual" })}>🏆 Podium</button></div></section>
        <section><Label><T value={{ ro: "Recapitulare", en: "Session recap" }} /></Label><div className="mt-2 grid grid-cols-2 gap-2"><a className="btn btn-dark btn-sm" href={api.exportUrl(room.id, youId, "json")} download>↓ JSON</a><a className="btn btn-dark btn-sm" href={api.exportUrl(room.id, youId, "html")} target="_blank" rel="noreferrer">▣ PDF / Print</a></div></section>
      </div>
      <footer className="grid grid-cols-2 gap-2 border-t border-white/10 p-4"><button className="btn btn-dark btn-sm" onClick={() => confirm(lang === "ro" ? "Resetezi activitatea pentru toată echipa?" : "Reset the activity for everyone?") && onReset()}>↺ <T value={{ ro: "Reset", en: "Reset" }} /></button><button className="btn btn-sm border border-rose-400/20 bg-rose-500/10 text-rose-200" onClick={() => confirm(lang === "ro" ? "Închizi sesiunea pentru toți?" : "Close the session for everyone?") && store.sendControl("close")}>■ <T value={{ ro: "Închide", en: "Close" }} /></button></footer>
    </aside>
  );
}
function Label({ children }: { children: React.ReactNode }) { return <div className="text-[10px] font-bold uppercase tracking-[.2em] text-ink-400">{children}</div>; }
