import assert from "node:assert/strict";
import { BASE, post, connect, send, until, barrier, close, delay, place } from "./realtime-client.mjs";

const clients = [];
const ready = async (room, identity) => { const c = await connect(room.id, identity); clients.push(c); return c; };
async function join(room, name) {
  const result = await post(`/api/rooms/${room.id}/join`, { name, code: room.code });
  assert.equal(result.status, 200);
  return result.data;
}
const view = async id => (await fetch(BASE + `/api/rooms/${id}`).then(r => r.json())).room;
try {
  const defaults = await post("/api/rooms", { puzzleId: "starry-night", difficulty: "kids", name: "Default host" });
  assert.equal(defaults.data.room.podiumEnabled, false, "Cooperation is the default");
  const made = await post("/api/rooms", { puzzleId: "starry-night", difficulty: "kids", name: "Facilitator", role: "spectator", podiumEnabled: true });
  assert.equal(made.status, 200);
  const { room } = made.data;
  assert.equal(room.maxPlayers, 25);
  assert.equal(room.maxObservers, 1);
  const host = await ready(room, made.data);
  const aId = await join(room, "Ana"), bId = await join(room, "Bogdan");
  const a = await ready(room, aId), b = await ready(room, bId);
  const pieces = [...a.pieces.values()];
  send(host, { t: "control", action: "start" });
  await until(a, c => c.room.stage === "play");
  const startedAt = a.room.startedAt;
  const cId = await join(room, "Carmen"), c = await ready(room, cId);
  await place(a, pieces[0]);
  await place(b, pieces[1]);
  await until(host, c => c.scores.reduce((sum, s) => sum + s.placed, 0) === 2);
  assert.ok(host.scores.filter(s => s.placed === 1).every(s => s.rank === 1), "Equal scores share first place");
  assert.ok(!host.scores.some(s => s.playerId === host.id), "Observer is outside the scoring population");
  assert.equal(host.scores.find(s => s.playerId === c.id).rank, null, "Zero placements do not earn medals");
  send(a, { t: "piece", id: 0, x: pieces[0].correctX, y: pieces[0].correctY, drag: false });
  send(a, { t: "piece", id: 2, x: -1000, y: -1000, drag: true });
  send(a, { t: "piece", id: 2, x: -1000, y: -1000, drag: false });
  send(host, { t: "piece", id: 2, x: pieces[2].correctX, y: pieces[2].correctY, drag: false });
  await Promise.all([barrier(a), barrier(host)]);
  assert.equal(host.scores.reduce((sum, s) => sum + s.placed, 0), 2, "Movement, repeated drops and observer input do not earn points");
  send(c, { t: "control", action: "lock", locked: true });
  await until(c, c => c.events.some(m => m.t === "error" && m.code === "not_host"));
  await delay(120);
  send(host, { t: "control", action: "lock", locked: true });
  await Promise.all([host, a, b, c].map(c => until(c, c => c.room.boardLocked && !!c.room.pausedAt)));
  const paused = await view(room.id);
  await delay(250);
  assert.equal((await view(room.id)).elapsedMs, paused.elapsedMs, "Pause excludes waiting from team time");
  send(host, { t: "control", action: "start" });
  await until(host, c => c.events.some(m => m.t === "error" && m.code === "already_started"));
  assert.equal((await view(room.id)).pausedAt, paused.pausedAt, "Repeated Start cannot bypass or corrupt a pause");
  send(a, { t: "piece", id: 2, x: pieces[2].correctX, y: pieces[2].correctY, drag: false });
  await barrier(a);
  assert.equal(a.pieces.get(2).locked, false, "Paused board rejects placement");
  send(host, { t: "control", action: "lock", locked: false });
  await until(a, c => !c.room.boardLocked && !c.room.pausedAt);
  await delay(120);
  assert.ok((await view(room.id)).elapsedMs >= paused.elapsedMs + 100, "Time resumes");
  assert.equal((await post(`/api/rooms/${room.id}/replay`, {}, made.data.credential)).status, 409, "An unfinished round cannot replay");
  for (let id = 2; id <= 5; id++) await place(a, pieces[id]);
  for (let id = 7; id <= 11; id++) await place(b, pieces[id]);
  await close(b);
  await until(a, c => !c.players.some(p => p.id === b.id));
  const returned = await post(`/api/rooms/${room.id}/join`, { pid: bId.playerId, name: "Bogdan" }, bId.credential);
  assert.equal(returned.status, 200);
  const reconnected = await ready(room, bId);
  assert.equal(reconnected.scores.find(s => s.playerId === b.id).placed, 6, "Reconnect retains earned contribution");
  await close(reconnected);
  await until(a, c => !c.players.some(p => p.id === b.id));
  await place(a, pieces[6]);
  await until(host, c => c.room.completed);
  assert.deepEqual(host.scores.map(s => [s.name, s.placed, s.rank]), [["Ana", 6, 1], ["Bogdan", 6, 1], ["Carmen", 0, null]]);
  assert.deepEqual(new Set(host.room.completionPlayers), new Set(["Ana", "Bogdan", "Carmen"]), "Late joiners and disconnected contributors are retained; observer excluded");
  const finished = await view(room.id);
  await delay(220);
  assert.equal((await view(room.id)).elapsedMs, finished.completedInMs, "Final team time is frozen");
  assert.equal((await post(`/api/rooms/${room.id}/replay`, {}, aId.credential)).status, 403, "Only facilitator/host can replay");
  const replay = await post(`/api/rooms/${room.id}/replay`, {}, made.data.credential);
  assert.equal(replay.status, 200);
  await until(a, c => c.room.startedAt !== startedAt && !c.room.completed);
  assert.equal(a.room.podiumEnabled, true);
  assert.equal(a.room.stage, "play");
  assert.equal(a.room.boardLocked, false);
  assert.ok(a.room.elapsedMs < 100);
  assert.ok([...a.pieces.values()].every(p => !p.locked && !p.heldBy));
  assert.equal(a.scores.reduce((sum, s) => sum + s.placed, 0), 0);
  assert.equal(a.scores.some(s => s.playerId === b.id), false, "Previous offline players are outside the new round");
  assert.equal(a.players.length, 3, "Connected group stays together");
  await place(a, pieces[0]);
  assert.equal(a.scores.find(s => s.playerId === a.id).placed, 1);
  const changed = await post(`/api/rooms/${room.id}/puzzle`, { puzzleId: "mona-lisa", difficulty: "kids" }, made.data.credential);
  assert.equal(changed.status, 200);
  await until(a, c => c.room.stage === "lobby");
  assert.equal(a.room.podiumEnabled, true);
  assert.equal(a.room.elapsedMs, 0);
  console.log("PASS optional podium, fair scoring, shared ties, zero-score and observer exclusion");
  console.log("PASS authorized pause/resume, frozen final time and duplicate-start protection");
  console.log("PASS late/disconnected participants, authenticated reconnect and fresh replay with the same group");
} finally { await Promise.all(clients.map(close)); }
